services:
  api:
    image: go-chat-app-api
    hostname: go-chat-app-api
    networks:
      - main-nw
    # not exposing ports, because all traffic goes through nginx-server via compose network
  nginx-server:
    image: go-chat-app-api-reverse-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - main-nw
networks:
  main-nw: