http {
    #limit_req_zone $http_x_forwarded_for zone=limitbyaddr:16m rate=3r/s;
    #limit_req_status  429;

    server {
        listen 80; 
        #uncom for ssl
        listen 443 ssl;
        server_name samuraichat.net;
        #uncom for ssl
        ssl_certificate /certs/fullchain.pem;
        ssl_certificate_key /certs/privkey.pem;
        
        location /users/me/avatar{
            client_max_body_size 10M;
            proxy_pass http://upload:8080/users/me/avatar;
        }

        location / {
            #limit_req zone=limitbyaddr;
            proxy_pass http://api:8080/;
        }

        location /ws {
            proxy_pass http://testws:8080/ws;
            # websocket support
            proxy_set_header Upgrade "websocket";
            proxy_set_header Connection "upgrade";
            #proxy_http_version 1.1;
        }
    }
}

events {}